// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLO4rEmTOsZF1VkNEn-_vXI5oAK2XujAs',
    appId: '1:769509512529:web:5177bf7c6da00eb49d2f70',
    messagingSenderId: '769509512529',
    projectId: 'trucker-compass',
    authDomain: 'trucker-compass.firebaseapp.com',
    storageBucket: 'trucker-compass.firebasestorage.app',
    measurementId: 'G-RD0GHS1HQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY9qRRITEbNOZUPA_Pwf-kRGYtWn3oC-s',
    appId: '1:769509512529:android:4cf2fb284c7826869d2f70',
    messagingSenderId: '769509512529',
    projectId: 'trucker-compass',
    storageBucket: 'trucker-compass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA99_jnB-PkDzPWktELmZxS2iaGF6owt1g',
    appId: '1:769509512529:ios:d4c8d192f251e2419d2f70',
    messagingSenderId: '769509512529',
    projectId: 'trucker-compass',
    storageBucket: 'trucker-compass.firebasestorage.app',
    iosBundleId: 'com.example.truckerCompass',
  );
}
